### ISSUE TITLE
Consider getting rid of Save changes popup

### ISSUE THREAD

**Issue by jkovzels** [sebbouez/PageFabric#1]
Noone is making changes to discard then when they go to the next page. If user needs to correct mistake, it should be accomplished by Undo command.

![image](https://user-images.githubusercontent.com/351671/79698273-371c8300-8288-11ea-962a-333ce409fde8.png)

**Comment by sebbouez** [comment]
This behavior will be more user friendly with the next release.
UI will support editing multiple documents at the same time with tabs. It will be easier to switch rapidly between open documents. The popup message will still be there when the user will close a tab.

**Comment by sebbouez** [comment]
Editor behavior changed in last release.
